name: prod
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 切代码到 runner
      - name: Checkout repository
        uses: actions/checkout@v1
        with:
          submodules: recursive
      # 下载 git submodule
      - name: Update submodules
        run: |
          git submodule update --remote
      - name: 安装项目依赖
        run: npm install
      - name: 打包
        run: npm build
      - name: 发布到服务器上
        uses: appleboy/scp-action@master
        with:
          source: "abstract-vue/*"
          host: ${{ secrets.HOST }}
          target: "/usr/src/zhoubichuan/prod/"
          port:  ${{ secrets.PORT }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
