name: prod
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 使用库中的代码
      - uses: actions/checkout@v1
      - name: 安装 Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "13.0.0"
      - name: 打包
        run: npm run build
      - name: 发布到服务器上
        uses: appleboy/scp-action@master
        with:
          source: "abstract-vue/*"
          host: ${{ secrets.HOST }}
          target: "/usr/src/zhoubichuan/prod/"
          port:  ${{ secrets.PORT }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
